#!/bin/bash
ORACLE_HOME=/u01/app/oracle/product/19.3.0/db_1
ORACLE_SID=TEST
PATH=$PATH:$ORACLE_HOME/bin
DD=`date +%Y-%m-%d-%H-%M-%S`
export ORACLE_HOME ORACLE_SID PATH DD
mkdir /mnt/or-bk-dev/TEST/${DD}
LOGFILE=/mnt/or-bk-dev/TEST/logs/daily_rman_TEST_bkup_`date +%Y%m%d`.log
rman target / nocatalog LOG $LOGFILE <<EOF
crosscheck backup;
crosscheck archivelog all;
run
{
backup as compressed backupset incremental level 1 DEVICE TYPE DISK TAG='INCREMENTAL_DATABASE' FORMAT '/mnt/or-bk-dev/TEST/${DD}/INCREMENTAL_BACKUP_%D_%T_%s-%p' check logical database plus archivelog;
backup current controlfile format '/mnt/or-bk-dev/TEST/${DD}/ControlFile_%d_%I_%u.ctl';
sql "create pfile=''/mnt/or-bk-dev/TEST/${DD}/pfileTEST.ora''from spfile";
backup spfile format '/mnt/or-bk-dev/TEST/${DD}/spfileTEST.ora';
}
EOF

*          *                                          *
| -------- | ---------------------------------------- |
| Variable | Description                              |
| -------- | ---------------------------------------- |
| `%d`     | Database name                            |
| `%I`     | Database ID (DBID)                       |
| `%u`     | Unique backup filename generated by RMAN |
| -------- | ---------------------------------------- |
| `%D`     | Day of Month                             |
| `%T`     | Date (YYYYMMDD)                          |
| -------- | ---------------------------------------- |
| `%s`     | Backup Set Number                        |
| `%p`     | Backup Piece Number                      |
| -------- | ---------------------------------------- |
*          *                                          *

OUTPUT:
INCREMENTAL_BACKUP_08_20260708_20026-1
INCREMENTAL_BACKUP_08_20260708_20027-1
INCREMENTAL_BACKUP_08_20260708_20028-1
...
INCREMENTAL_BACKUP_08_20260708_20042-1

Backup Set
    │
    ├── Backup Piece 1
    ├── Backup Piece 2
    └── Backup Piece 3
    
Backup Set 20048
    ├── Piece 1
    ├── Piece 2
    ├── Piece 3
    └── Piece 4

* Backup Set = Logical container.
* Backup Piece = Physical backup file.

* One Backup Set can contain one or more Backup Pieces.

This happens if:
- the backup exceeds MAXPIECESIZE.
- RMAN splits the backup into multiple pieces.

Example:

run
{
backup
as compressed backupset
maxpiecesize 2G
database;
}

Result:

Backup Set 20042
   ├── Piece 1
   ├── Piece 2
   └── Piece 3


---------------------------------------------------------
* A Backup Piece belongs to only one Backup Set.
---------------------------------------------------------

* One Backup Job (Full / Incremental) can create one or more Backup Sets.

This happens if:

1. You use multiple channels.

run
{
allocate channel c1 device type disk;
allocate channel c2 device type disk;
allocate channel c3 device type disk;

backup as compressed backupset database;

release channel c1;
release channel c2;
release channel c3;
}

---------------------------------------------------------

2. You configure Parallelism.

CONFIGURE DEVICE TYPE DISK PARALLELISM 3;

run
{
backup database;
}

---------------------------------------------------------

3. You use FILESPERSET.

run
{
backup
filesperset 4 --Each Backup Set can contain up to 4 Datafiles.
database;
}

FILESPERSET controls how many Datafiles are included in one Backup Set.

---------------------------------------------------------

4. RMAN may automatically create multiple Backup Sets based on:
- Number of Datafiles.
- Size of Datafiles.
- Backup optimization.

Example:

Backup Job
│
├── Backup Set 20026
│      ├── Datafile 2
│      ├── Datafile 11
│      └── Piece 1
│
├── Backup Set 20027
│      ├── Datafile 3
│      ├── Datafile 7
│      └── Piece 1
│
└── Backup Set 20044
       ├── Datafile 20
       └── Piece 1

---------------------------------------------------------

Useful Queries

-- Show Backup Sets and Backup Pieces

SELECT set_stamp,
       set_count,
       piece#,
       handle
FROM v$backup_piece
ORDER BY set_count;

---------------------------------------------------------

-- Show which Datafiles belong to each Backup Set

SELECT set_count,
       file#
FROM v$backup_datafile
ORDER BY set_count, file#;

---------------------------------------------------------
